# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.srcs/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0.xci
# IP: The module: 'mb_hdmi_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.srcs/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0.xci
# IP: The module: 'mb_hdmi_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
