# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_fa24/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_hdmi/mb_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi || ORIG_REF_NAME==mb_hdmi} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_0/mb_hdmi_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_dlmb_v10_0/mb_hdmi_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_dlmb_v10_0 || ORIG_REF_NAME==mb_hdmi_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_ilmb_v10_0/mb_hdmi_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_ilmb_v10_0 || ORIG_REF_NAME==mb_hdmi_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_dlmb_bram_if_cntlr_0/mb_hdmi_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_hdmi_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_ilmb_bram_if_cntlr_0/mb_hdmi_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_hdmi_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_lmb_bram_0/mb_hdmi_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_lmb_bram_0 || ORIG_REF_NAME==mb_hdmi_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_xbar_0 || ORIG_REF_NAME==mb_hdmi_xbar_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_axi_periph_0/mb_hdmi_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_axi_intc_0/mb_hdmi_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_mdm_1_0/mb_hdmi_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_mdm_1_0 || ORIG_REF_NAME==mb_hdmi_mdm_1_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_clk_wiz_1_0/mb_hdmi_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_clk_wiz_1_0 || ORIG_REF_NAME==mb_hdmi_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_rst_clk_wiz_1_100M_0/mb_hdmi_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_hdmi_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_uartlite_0_0/mb_hdmi_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==mb_hdmi_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_gpio_0_0/mb_hdmi_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_gpio_0_0 || ORIG_REF_NAME==mb_hdmi_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_gpio_0_1/mb_hdmi_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_gpio_0_1 || ORIG_REF_NAME==mb_hdmi_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_gpio_0_2/mb_hdmi_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_gpio_0_2 || ORIG_REF_NAME==mb_hdmi_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_timer_0_0/mb_hdmi_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_timer_0_0 || ORIG_REF_NAME==mb_hdmi_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_quad_spi_0_0/mb_hdmi_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_hdmi_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_xlconcat_0_0/mb_hdmi_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_xlconcat_0_0 || ORIG_REF_NAME==mb_hdmi_xlconcat_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_hdmi_text_controller_0_0_1/mb_hdmi_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_hdmi_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/jacob/Documents/UIUC/ECE/ECE_385/Final_Project_V7/Pacman/Pacman.gen/sources_1/bd/mb_hdmi/mb_hdmi_ooc.xdc
